import React from 'react';

import Location from './frontend/location.inline.svg';
import Globe from './frontend/globe.inline.svg';
import Google from './frontend/google.inline.svg';
import Facebook from './frontend/facebook.inline.svg';
import Twitter from './frontend/twitter.inline.svg';
import Linkedin from './frontend/linkedin.inline.svg';
import Instagram from './frontend/instagram.inline.svg';
import Youtube from './frontend/youtube.inline.svg';
import Word from './frontend/word.inline.svg';
import Audio from './frontend/audio.inline.svg';
import Excel from './frontend/excel.inline.svg';
import File from './frontend/file.inline.svg';
import Pdf from './frontend/pdf.inline.svg';
import Attachment from './frontend/attachment.inline.svg';
import Search from './frontend/search.inline.svg';
import Close from './frontend/close.inline.svg';
import Note from './frontend/note.inline.svg';
import Org from './frontend/org.inline.svg';
import Timesheet from './frontend/timesheet.inline.svg';
import Brief from './frontend/brief.inline.svg';
import Skill from './frontend/skill.inline.svg';
import Chat from './frontend/chat.inline.svg';
import Expand from './frontend/expand.inline.svg';
import Minimize from './frontend/minimize.inline.svg';
import Project from './frontend/project.inline.svg';
import Assessment from './frontend/assessment.inline.svg';
import Talent from './frontend/talent.inline.svg';
import Profile from './frontend/profile.inline.svg';
import Profile2 from './frontend/profile2.inline.svg';
import ChatUsers from './frontend/chat-users.inline.svg';
import Down from './frontend/down.inline.svg';
import Company from './frontend/company.inline.svg';
import Dashboard from './frontend/dashboard.inline.svg';
import Quote from './frontend/quote.inline.svg';
import Guide from './frontend/guide.inline.svg';
import Reference from './frontend/reference.inline.svg';
import Question from './frontend/question.inline.svg';
import Caret from './frontend/caret.inline.svg';
import Link from './frontend/link.inline.svg';
import Pencil from './frontend/pencil.inline.svg';
import Picture from './frontend/picture.inline.svg';
import StarEmpty from './frontend/star.empty.inline.svg';
import StarFull from './frontend/star.full.inline.svg';
import External from './frontend/external.inline.svg';
import Wallet from './frontend/wallet.inline.svg';
import Help from './frontend/help.inline.svg';
import Activity from './frontend/activity.inline.svg';
import Notification from './frontend/notification.inline.svg';
import Ok from './frontend/ok.inline.svg';
import Phone from './frontend/phone.inline.svg';
import Email from './frontend/email.inline.svg';
import Add from './frontend/add.inline.svg';
import More from './frontend/more.inline.svg';
import MoreVertical from './frontend/more-vertical.inline.svg';
import Menu from './frontend/menu.inline.svg';
import Settings from './frontend/settings.inline.svg';
import Intercom from './frontend/intercom.inline.svg';
import Text from './frontend/text.inline.svg';
import Logout from './frontend/logout.inline.svg';

const Icon = (props) => {
  return <div />;
};

Icon.Location = Location;
Icon.Globe = Globe;
Icon.Google = Google;
Icon.Facebook = Facebook;
Icon.Twitter = Twitter;
Icon.Linkedin = Linkedin;
Icon.Instagram = Instagram;
Icon.Youtube = Youtube;
Icon.Word = Word;
Icon.Audio = Audio;
Icon.Excel = Excel;
Icon.File = File;
Icon.Pdf = Pdf;
Icon.Attachment = Attachment;
Icon.Search = Search;
Icon.Close = Close;
Icon.Note = Note;
Icon.Org = Org;
Icon.Timesheet = Timesheet;
Icon.Brief = Brief;
Icon.Skill = Skill;
Icon.Chat = Chat;
Icon.Expand = Expand;
Icon.Minimize = Minimize;
Icon.Project = Project;
Icon.Assessment = Assessment;
Icon.Talent = Talent;
Icon.Profile = Profile;
Icon.Profile2 = Profile2;
Icon.ChatUsers = ChatUsers;
Icon.Down = Down;
Icon.Company = Company;
Icon.Dashboard = Dashboard;
Icon.Quote = Quote;
Icon.Guide = Guide;
Icon.Reference = Reference;
Icon.Question = Question;
Icon.Caret = Caret;
Icon.Link = Link;
Icon.Pencil = Pencil;
Icon.Picture = Picture;
Icon.StarEmpty = StarEmpty;
Icon.StarFull = StarFull;
Icon.External = External;
Icon.Wallet = Wallet;
Icon.Help = Help;
Icon.Activity = Activity;
Icon.Notification = Notification;
Icon.Ok = Ok;
Icon.Phone = Phone;
Icon.Email = Email;
Icon.Add = Add;
Icon.More = More;
Icon.MoreVertical = MoreVertical;
Icon.Menu = Menu;
Icon.Settings = Settings;
Icon.Intercom = Intercom;
Icon.Text = Text;
Icon.Logout = Logout;
export default Icon;
