import React from 'react';
import External from './icons/external.inline.svg';
import Add from './icons/add.inline.svg';
import Close from './icons/close.inline.svg';
import Logout from './icons/logout.inline.svg';
import Home from './icons/home.inline.svg';
import Talent from './icons/talent.inline.svg';
import Brief from './icons/brief.inline.svg';
import Profile from './icons/profile.inline.svg';
import Down from './icons/down.inline.svg';
import Drag from './icons/drag.inline.svg';
import Edit from './icons/edit.inline.svg';
import Preview from './icons/preview.inline.svg';
import More from './icons/more.inline.svg';
import Search from './icons/search.inline.svg';
import User from './icons/user.inline.svg';
import Xero from './icons/xero.inline.svg';
import Refresh from './icons/refresh.inline.svg';
import Filter from './icons/filter.inline.svg';
import Email from './icons/email.inline.svg';
import Split from './icons/split.inline.svg';
import Minimize from './icons/minimize.inline.svg';
import Company from './icons/company.inline.svg';
import Timesheet from './icons/timesheets.inline.svg';
import Invoice from './icons/invoice.inline.svg';
import Paperclip from './icons/paperclip.inline.svg';
import Stretch from './icons/stretch.inline.svg';
import Shrink from './icons/shrink.inline.svg';
import ChevronLeft from './icons/left.inline.svg';
import ChevronRight from './icons/right.inline.svg';
import Play from './icons/play.inline.svg';
import Stop from './icons/stop.inline.svg';
import Folder from './icons/folder.inline.svg';

import MinimizeSmall from './small/minimize.inline.svg';
import SplitSmall from './small/split.inline.svg';
import EditSmall from './small/edit.inline.svg';
import BinSmall from './small/bin.inline.svg';
import ChevronDownSmall from './small/down.inline.svg';
import CloseSmall from './small/close.inline.svg';
import UpSmall from './small/up.inline.svg';

import ExpandExtraSmall from './xs/expand.inline.svg';
import CollapseExtraSmall from './xs/collapse.inline.svg';
import MoreExtraSmall from './xs/more.inline.svg';

const Icon = (props) => {
  return <div />;
};

Icon.External = External;
Icon.Add = Add;
Icon.Close = Close;
Icon.Logout = Logout;
Icon.Home = Home;
Icon.Talent = Talent;
Icon.Profile = Profile;
Icon.Brief = Brief;
Icon.Down = Down;
Icon.Drag = Drag;
Icon.Edit = Edit;
Icon.Preview = Preview;
Icon.More = More;
Icon.User = User;
Icon.Search = Search;
Icon.Xero = Xero;
Icon.Refresh = Refresh;
Icon.Filter = Filter;
Icon.Email = Email;
Icon.Split = Split;
Icon.Minimize = Minimize;
Icon.MinimizeSmall = MinimizeSmall;
Icon.SplitSmall = SplitSmall;
Icon.Company = Company;
Icon.Timesheet = Timesheet;
Icon.ExpandExtraSmall = ExpandExtraSmall;
Icon.CollapseExtraSmall = CollapseExtraSmall;
Icon.MoreExtraSmall = MoreExtraSmall;
Icon.EditSmall = EditSmall;
Icon.BinSmall = BinSmall;
Icon.Invoice = Invoice;
Icon.ChevronDownSmall = ChevronDownSmall;
Icon.CloseSmall = CloseSmall;
Icon.UpSmall = UpSmall;
Icon.Paperclip = Paperclip;
Icon.Stretch = Stretch;
Icon.Shrink = Shrink;
Icon.ChevronLeft = ChevronLeft;
Icon.ChevronRight = ChevronRight;
Icon.Play = Play;
Icon.Stop = Stop;
Icon.Folder = Folder;

export default Icon;
