import React from 'react';

import Drag from './icons/drag.inline.svg';
import Preview from './icons/preview.inline.svg';
import Xero from './icons/xero.inline.svg';
import Refresh from './icons/refresh.inline.svg';
import Filter from './icons/filter.inline.svg';
import Split from './icons/split.inline.svg';
import Invoice from './icons/invoice.inline.svg';
import Play from './icons/play.inline.svg';
import Stop from './icons/stop.inline.svg';

import Google from './social/google.inline.svg';
import Facebook from './social/facebook.inline.svg';
import Twitter from './social/twitter.inline.svg';
import Linkedin from './social/linkedin.inline.svg';
import Instagram from './social/instagram.inline.svg';
import Youtube from './social/youtube.inline.svg';
import Word from './icons/word.inline.svg';
import Audio from './icons/audio.inline.svg';
import Excel from './icons/excel.inline.svg';
import File from './icons/file.inline.svg';
import Pdf from './icons/pdf.inline.svg';
import Attachment from './icons/attachment.inline.svg';
import Search from './icons/search.inline.svg';
import Close from './icons/close.inline.svg';
import Org from './icons/org.inline.svg';
import Timesheet from './icons/timesheet.inline.svg';
import Brief from './icons/brief.inline.svg';
import Skill from './icons/skill.inline.svg';
import Chat from './icons/chat.inline.svg';
import Expand from './icons/expand.inline.svg';
import Minimize from './icons/minimize.inline.svg';
import Project from './icons/project.inline.svg';
import Assessment from './icons/assessment.inline.svg';
import Talent from './icons/talent.inline.svg';
import Profile from './icons/profile.inline.svg';
import ChatUsers from './icons/chat-users.inline.svg';
import Down from './icons/down.inline.svg';
import Download from './icons/download.inline.svg';
import Company from './icons/company.inline.svg';
import Dashboard from './icons/dashboard.inline.svg';
import Guide from './icons/guide.inline.svg';
import Reference from './icons/reference.inline.svg';
import Caret from './icons/caret.inline.svg';
import Link from './icons/link.inline.svg';
import Pencil from './icons/pencil.inline.svg';
import Picture from './icons/picture.inline.svg';
import StarEmpty from './icons/star.empty.inline.svg';
import StarFull from './icons/star.full.inline.svg';
import External from './icons/external.inline.svg';
import Activity from './icons/activity.inline.svg';
import Notification from './icons/notification.inline.svg';
import Ok from './icons/ok.inline.svg';
import Phone from './icons/phone.inline.svg';
import Email from './icons/email.inline.svg';
import Add from './icons/add.inline.svg';
import More from './icons/more.inline.svg';
import MoreVertical from './icons/more-vertical.inline.svg';
import Settings from './icons/settings.inline.svg';
import Question from './icons/question.inline.svg';
import Text from './icons/text.inline.svg';
import Logout from './icons/logout.inline.svg';
import Menu from './icons/menu.inline.svg';

// TODO TRITONE ICONS

const Icon = (props) => {
  return <div />;
};

Icon.Google = Google;
Icon.Facebook = Facebook;
Icon.Twitter = Twitter;
Icon.Linkedin = Linkedin;
Icon.Instagram = Instagram;
Icon.Youtube = Youtube;
Icon.Word = Word;
Icon.Audio = Audio;
Icon.Excel = Excel;
Icon.File = File;
Icon.Pdf = Pdf;
Icon.Attachment = Attachment;
Icon.Search = Search;
Icon.Close = Close;
Icon.Org = Org;
Icon.Timesheet = Timesheet;
Icon.Brief = Brief;
Icon.Skill = Skill;
Icon.Chat = Chat;
Icon.Expand = Expand;
Icon.Minimize = Minimize;
Icon.Project = Project;
Icon.Assessment = Assessment;
Icon.Talent = Talent;
Icon.Profile = Profile;
Icon.ChatUsers = ChatUsers;
Icon.Download = Download;
Icon.Down = Down;
Icon.Company = Company;
Icon.Dashboard = Dashboard;
Icon.Guide = Guide;
Icon.Reference = Reference;
Icon.Caret = Caret;
Icon.Link = Link;
Icon.Pencil = Pencil;
Icon.Edit = Pencil;
Icon.Picture = Picture;
Icon.StarEmpty = StarEmpty;
Icon.StarFull = StarFull;
Icon.External = External;
Icon.Activity = Activity;
Icon.Notification = Notification;
Icon.Ok = Ok;
Icon.Phone = Phone;
Icon.Email = Email;
Icon.Add = Add;
Icon.More = More;
Icon.MoreVertical = MoreVertical;
Icon.Settings = Settings;
Icon.Question = Question;
Icon.Intercom = Question; // Fallback
Icon.Text = Text;
Icon.Logout = Logout;
Icon.Menu = Menu;

Icon.Drag = Drag;
Icon.Preview = Preview;
Icon.Xero = Xero;
Icon.Refresh = Refresh;
Icon.Filter = Filter;
Icon.Split = Split;

Icon.Invoice = Invoice;
Icon.Play = Play;
Icon.Stop = Stop;

export default Icon;
