import React, { memo } from 'react';

import Drag from './icons/drag.inline.svg';
import Preview from './icons/preview.inline.svg';
import Xero from './icons/xero.inline.svg';
import Refresh from './icons/refresh.inline.svg';
import Filter from './icons/filter.inline.svg';
import Split from './icons/split.inline.svg';
import Invoice from './icons/invoice.inline.svg';
import Play from './icons/play.inline.svg';
import Stop from './icons/stop.inline.svg';

import Google from './social/google.inline.svg';
import Facebook from './social/facebook.inline.svg';
import Twitter from './social/twitter.inline.svg';
import Linkedin from './social/linkedin.inline.svg';
import Instagram from './social/instagram.inline.svg';
import Youtube from './social/youtube.inline.svg';
import Word from './icons/word.inline.svg';
import Audio from './icons/audio.inline.svg';
import Excel from './icons/excel.inline.svg';
import File from './icons/file.inline.svg';
import Pdf from './icons/pdf.inline.svg';
import Attachment from './icons/attachment.inline.svg';
import Search from './icons/search.inline.svg';
import Close from './icons/close.inline.svg';
import Org from './icons/org.inline.svg';
import Timesheet from './icons/timesheet.inline.svg';
import Brief from './icons/brief.inline.svg';
import Skill from './icons/skill.inline.svg';
import Chat from './icons/chat.inline.svg';
import Expand from './icons/expand.inline.svg';
import Minimize from './icons/minimize.inline.svg';
import Project from './icons/project.inline.svg';
import Assessment from './icons/assessment.inline.svg';
import Talent from './icons/talent.inline.svg';
import Profile from './icons/profile.inline.svg';
import ChatUsers from './icons/chat-users.inline.svg';
import Down from './icons/down.inline.svg';
import Download from './icons/download.inline.svg';
import Company from './icons/company.inline.svg';
import Dashboard from './icons/dashboard.inline.svg';
import Guide from './icons/guide.inline.svg';
import Reference from './icons/reference.inline.svg';
import Caret from './icons/caret.inline.svg';
import Link from './icons/link.inline.svg';
import Pencil from './icons/pencil.inline.svg';
import Picture from './icons/picture.inline.svg';
import StarEmpty from './icons/star.empty.inline.svg';
import StarFull from './icons/star.full.inline.svg';
import External from './icons/external.inline.svg';
import Activity from './icons/activity.inline.svg';
import Notification from './icons/notification.inline.svg';
import Ok from './icons/ok.inline.svg';
import Phone from './icons/phone.inline.svg';
import Email from './icons/email.inline.svg';
import Add from './icons/add.inline.svg';
import More from './icons/more.inline.svg';
import MoreVertical from './icons/more-vertical.inline.svg';
import Settings from './icons/settings.inline.svg';
import Question from './icons/question.inline.svg';
import Text from './icons/text.inline.svg';
import Logout from './icons/logout.inline.svg';
import Menu from './icons/menu.inline.svg';

// TODO TRITONE ICONS

const Icon = (props) => {
  return <div />;
};

Icon.Google = memo(Google);
Icon.Facebook = memo(Facebook);
Icon.Twitter = memo(Twitter);
Icon.Linkedin = memo(Linkedin);
Icon.Instagram = memo(Instagram);
Icon.Youtube = memo(Youtube);
Icon.Word = memo(Word);
Icon.Audio = memo(Audio);
Icon.Excel = memo(Excel);
Icon.File = memo(File);
Icon.Pdf = memo(Pdf);
Icon.Attachment = memo(Attachment);
Icon.Search = memo(Search);
Icon.Close = memo(Close);
Icon.Org = memo(Org);
Icon.Timesheet = memo(Timesheet);
Icon.Brief = memo(Brief);
Icon.Skill = memo(Skill);
Icon.Chat = memo(Chat);
Icon.Expand = memo(Expand);
Icon.Minimize = memo(Minimize);
Icon.Project = memo(Project);
Icon.Assessment = memo(Assessment);
Icon.Talent = memo(Talent);
Icon.Profile = memo(Profile);
Icon.ChatUsers = memo(ChatUsers);
Icon.Download = memo(Download);
Icon.Down = memo(Down);
Icon.Company = memo(Company);
Icon.Dashboard = memo(Dashboard);
Icon.Guide = memo(Guide);
Icon.Reference = memo(Reference);
Icon.Caret = memo(Caret);
Icon.Link = memo(Link);
Icon.Pencil = memo(Pencil);
Icon.Edit = memo(Pencil);
Icon.Picture = memo(Picture);
Icon.StarEmpty = memo(StarEmpty);
Icon.StarFull = memo(StarFull);
Icon.External = memo(External);
Icon.Activity = memo(Activity);
Icon.Notification = memo(Notification);
Icon.Ok = memo(Ok);
Icon.Phone = memo(Phone);
Icon.Email = memo(Email);
Icon.Add = memo(Add);
Icon.More = memo(More);
Icon.MoreVertical = memo(MoreVertical);
Icon.Settings = memo(Settings);
Icon.Question = memo(Question);
Icon.Intercom = memo(Question); // Fallback
Icon.Text = memo(Text);
Icon.Logout = memo(Logout);
Icon.Menu = memo(Menu);

Icon.Drag = memo(Drag);
Icon.Preview = memo(Preview);
Icon.Xero = memo(Xero);
Icon.Refresh = memo(Refresh);
Icon.Filter = memo(Filter);
Icon.Split = memo(Split);

Icon.Invoice = memo(Invoice);
Icon.Play = memo(Play);
Icon.Stop = memo(Stop);

export default Icon;
